// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unikent.API.DbContext;

#nullable disable

namespace Unikent.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Unikent.API.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Density")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DormitoryPrices")
                        .HasColumnType("int");

                    b.Property<int>("DormitoryPricesMax")
                        .HasColumnType("int");

                    b.Property<int>("DormitoryPricesMin")
                        .HasColumnType("int");

                    b.Property<float>("GPopulation")
                        .HasColumnType("real");

                    b.Property<int>("MonthCoastMax")
                        .HasColumnType("int");

                    b.Property<int>("MonthCoastMin")
                        .HasColumnType("int");

                    b.Property<int>("MonthCost")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("NearCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NightLife")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("NightLifeEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("NigtLifeStart")
                        .HasColumnType("time");

                    b.Property<float>("OffenceInddex")
                        .HasColumnType("real");

                    b.Property<int>("RentPricesMax")
                        .HasColumnType("int");

                    b.Property<int>("RentPricesMin")
                        .HasColumnType("int");

                    b.Property<int>("SPopulationMax")
                        .HasColumnType("int");

                    b.Property<int>("SPopulationMin")
                        .HasColumnType("int");

                    b.Property<float>("SecurityIndexs")
                        .HasColumnType("real");

                    b.Property<float>("SocialScore")
                        .HasColumnType("real");

                    b.Property<string>("Transpor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeaatherMax")
                        .HasColumnType("int");

                    b.Property<int>("WeatherMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Unikent.API.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("MName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Unikent.API.Models.Request", b =>
                {
                    b.Property<Guid>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ImportanceCost")
                        .HasColumnType("int");

                    b.Property<int>("ImportanceSafety")
                        .HasColumnType("int");

                    b.Property<int>("ImportanceSocial")
                        .HasColumnType("int");

                    b.Property<Guid>("MId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MonthlyIncome")
                        .HasColumnType("int");

                    b.Property<float>("PrefersHotClimate")
                        .HasColumnType("real");

                    b.Property<int>("SPopulation")
                        .HasColumnType("int");

                    b.Property<bool>("WantsNatureLifestyle")
                        .HasColumnType("bit");

                    b.Property<bool>("WantsNightLife")
                        .HasColumnType("bit");

                    b.HasKey("RId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Unikent.API.Models.Result", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("ResultId");

                    b.HasIndex("CityId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Unikent.API.Models.Result", b =>
                {
                    b.HasOne("Unikent.API.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
